replicas: 2

sql:
  instance: ent-namtar-prd:europe-west1:namtar-db-1=tcp:5432

configMap:
  projectId: ent-marduk-prd
  gcsBucketName: marduk-exchange-production
  kafkaBrokers: entur-kafka-prod-ext-entur-prod.aivencloud.com:14019
  registryUrl: https://entur-kafka-prod-ext-entur-prod.aivencloud.com:14009
  kafkaEnabled: true
  topicName: dated-service-journeys-production
  importDisabled: true

ingress:
  enabled: true
  domainName: .entur.io