replicas: 2

sql:
  instance: ent-namtar-tst:europe-west1:namtar-db-1=tcp:5432

configMap:
  projectId: ent-marduk-tst
  gcsBucketName: marduk-exchange-test
  kafkaBrokers: entur-kafka-test-ext-entur-test.aivencloud.com:11877
  registryUrl: https://entur-kafka-test-ext-entur-test.aivencloud.com:11867
  kafkaEnabled: true
  topicName: dated-service-journeys-staging
  importDisabled: true

ingress:
  enabled: true
  domainName: .staging.entur.io
rbac:
  enabled: true