gcp_project            = "entur-ror-prod"
gcp_resources_project = "entur-ror-prod"
kube_namespace = "production"
storage_bucket_name="ror-marduk-exchange-production"
service_account_bucket_role="roles/storage.objectAdmin"