gcp_project            = "entur-ror-test"
gcp_resources_project = "entur-ror-test"
kube_namespace = "staging"
storage_bucket_name="ror-marduk-exchange-test"
service_account_bucket_role="roles/storage.objectAdmin"