replicas: 2


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  cpuLimit: 7500m
  memLimit: 6000Mi
  cpuRequest: 500m
  memRequest: 2000Mi
  xmx: 4500m


tmpDirectory:
  path: /home/appuser/tmp

configMapMount:
   name: namtar-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

