replicas: 2

sql:
  instance: ent-namtar-tst:europe-west1:namtar-db-1=tcp:5432

configMap:
  projectId: entur-ror-test
  gcsBucketName: ror-marduk-exchange-test
  kafkaBrokers: bootstrap.test-ext.kafka.entur.io:9095
  registryUrl: http://schema-registry.test-ext.kafka.entur.io:8001
  kafkaEnabled: true
  topicName: dated-service-journeys-staging
  importDisabled: false

ingress:
  enabled: true
  domainName: .staging.entur.io
rbac:
  enabled: true