replicas: 2

sql:
  instance: ent-namtar-prd:europe-west1:namtar-db-1=tcp:5432

configMap:
  projectId: ent-marduk-prd
  gcsBucketName: marduk-exchange-production
  kafkaBrokers: bootstrap.prod-ext.kafka.entur.io:9095
  registryUrl: http://schema-registry.prod-ext.kafka.entur.io:8001
  kafkaEnabled: true
  topicName: dated-service-journeys-production
  importDisabled: false

ingress:
  enabled: true
  domainName: .entur.io