env: dev

replicas: 2


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  cpuLimit: 7500m
  memLimit: 6000Mi
  cpuRequest: 500m
  memRequest: 2000Mi
  xmx: 4500m

secretMount:
   name: namtar-key
   mountPath: /etc/namtar/credentials.json
   subPath: credentials.json
   secretName: ror-namtar-sa-key
   readOnly: true


configMapMount:
   name: namtar-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

ingress:
    enabled: true
    devIp: 35.195.223.29
    stagingIp: 35.195.146.93
    productionIp: 35.187.15.14
