replicas: 2

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  memLimit: 6000Mi
  cpuRequest: 500m
  memRequest: 2000Mi
  xmx: 4500m


tmpDirectory:
  path: /home/appuser/tmp

configMapMount:
   name: namtar-config

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

secrets:
  kafka:
    - KAFKA_SSL_CREDENTIALS
    - NAMTAR_KAFKA_SASL_USERNAME
    - NAMTAR_KAFKA_SASL_PASSWORD
  namtar-psql-credentials:
    - SPRING_DATASOURCE_PASSWORD
