apiVersion: v1
data:
  application.properties: |-
    namtar.import.disabled=true
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}