apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /health/scrape
        prometheus.io/port: '{{ .Values.service.http.internalPort }}'
        prometheus.io/scrape: 'true'
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.15
          imagePullPolicy: IfNotPresent
          command:
                - /cloud_sql_proxy
                - -instances={{ .Values.sql.instance }}
                - -credential_file=/etc/namtar/credentials.json
                - -log_debug_stdout
          resources:
            requests:
              cpu: 50m
              memory: 40Mi
          volumeMounts:
            - mountPath: /etc/namtar
              name: {{ .Values.secretMount.name }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.identifier }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            - name: JAVA_OPTIONS
              value: -server -Xmx{{ .Values.resources.xmx }} -Dspring.config.additional-location=/etc/application-config/application.properties
                  -Dfile.encoding=UTF-8
            - name: TZ
              value: Europe/Oslo
            - name: KAFKA_SSL_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: kafka-ssl-credentials
                  name: ror-namtar-secrets
            - name: NAMTAR_KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: kafka-user-name
                  name: ror-namtar-secrets
            - name: NAMTAR_KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: kafka-user-password
                  name: ror-namtar-secrets
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: namtar-db-password
                  name: ror-namtar-secrets
          resources:
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memLimit }}
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memRequest }}
          volumeMounts:
            - name: {{ .Values.secretMount.name }}
              mountPath: {{ .Values.secretMount.mountPath }}
              subPath: {{ .Values.secretMount.subPath }}
              readOnly: {{ .Values.secretMount.readOnly }}
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
          ports:
            - containerPort: {{ .Values.service.http.internalPort }}
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/up
              port: {{ .Values.service.http.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 240
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: {{ .Values.service.http.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31
      volumes:
        - name: {{ .Values.secretMount.name }}
          secret:
            secretName: {{ .Values.secretMount.secretName }}
        - name: application-config
          configMap:
            name: {{ .Values.configMapMount.name }}
            defaultMode: 420

